### ISSUE TITLE
Add a way to derive via

### ISSUE THREAD

**Issue by k-bx** [haskell-hvr/newtype#2]
DerivingVia provides a concise way to avoid boilerplate. I've managed to get something working, but there might be a better way to achieve this. My implementation requires a new class that would have our newtype as last parameter, thus I've introduced a `NewtypeBack`.

```haskell
newtype DNewtype a =
  DNewtype a

instance Newtype (DNewtype a) a where
  pack = DNewtype
  unpack (DNewtype x) = x

instance NewtypeBack a (DNewtype a) where
  oToN = DNewtype
  nToO (DNewtype x) = x

class NewtypeBack o n | n -> o where
  oToN :: o -> n
  nToO :: n -> o

instance NewtypeBack n o => Newtype o n where
  pack = oToN
  unpack = nToO
```

Usage now looks like this:

```haskell
newtype WorkId =
  WorkId Int
  deriving (Show, Eq, Generic)
  deriving (NewtypeBack Int) via DNewtype Int
```

What do you think? Should we incorporate something like this?

**Comment by k-bx** [comment]
Forgot to mention, this requires `{-# LANGUAGE UndecidableInstances #-}`, which doesn't look nice.

**Comment by hvr** [comment]
@k-bx btw, have you seen #1 ? I'm wondering what the benefit of the DerivingVia approach is over the IMO much simpler one in #1

**Comment by hvr** [comment]
To give an example, with #1 you basically just say

```hs
newtype WorkId = WorkId Int deriving (Show, Eq)

instance Newtype WorkId Int
```

...or the respective DerivingVia form if you don't care about compatibility with GHC 7.8

**Comment by k-bx** [comment]
Ooh, that would be very good indeed! I would just use it instead of DerivingVia (at least in current form).

**Comment by k-bx** [comment]
https://github.com/haskell-hvr/newtype/pull/1 is good enough, I see no point in this DerivingVia stuff
