### ISSUE TITLE
Support ghc 9.0.1?

### ISSUE THREAD

**Issue by emberdart** [haskell-hvr/newtype#4]
Unsure if it's simply bounds or issues.

Thanks!

**Comment by andreasabel** [comment]
`cabal install newtype --allow-newer` builds, so a revision could be enough.  The package contains no tests though.  
Relaxation of the bounds on `base` and `transformers` could be requested on https://github.com/haskell-infra/hackage-trustees/issues.  (I won't do it myself, as I am not a user of this project.)

**Comment by andreasabel** [comment]
Done: https://hackage.haskell.org/package/newtype-0.2.2.0/revisions/
