### ISSUE TITLE
Consider renaming *pack to *wrap

### ISSUE THREAD

**Issue by jerbaroo** [haskell-hvr/newtype#6]
- Wrapping and unwrapping newtypes is the usual terminology when dealing with newtypes. When someone reads `unwrap` they are more likely to infer the operation has to do with newtypes, whereas pack is already familiar from non-newtypes such as `Text` and `ByteString`.
- The `Control.NewType` typeclass uses the terminology unwrap in the documentation "Given a newtype n, we will always have the same unwrapped type o".
- For consistency with other typeclasses which are mentioned in the `Control.Newtype` haddocks: `WrappedMonad` and `WrappedArrow`.
- Consistency with the PureScript `NewType` typeclass: https://pursuit.purescript.org/packages/purescript-newtype/4.0.0/docs/Data.Newtype#v:unwrap

**Comment by andreasabel** [comment]
While the names you suggest seem better than the existing ones, I am not inclined to change the old ones, since then the users will either have to change their code or pin to an old version of `newtype`.
This extra work load on existing users has to be balanced with aesthetics such as better names for the operations.
I am inclined to keep this package stable---it has been virtually unchanged for years now.

**Comment by jerbaroo** [comment]
> since then the users will either have to change their code or pin to an old version of newtype.

If there is agreement that the names can be improved, then we should be able to accomplish that without breaking backwards compatibility, perhaps _something along the lines_ of:

```hs
class NewType n o | n -> o where
  wrap :: o -> n
  default wrap :: Coercible o n => o -> n
  wrap = coerce
  
  unwrap :: n -> o
  default unwrap :: Coercible  n o => n -> o
  unwrap = coerce
  
  {-# DEPRECATED #-}
  pack :: o -> n
  default pack :: Coercible o n => o -> n
  pack = wrap -- Now using wrap.

  {-# DEPRECATED #-}
  unpack :: n -> o
  default unpack :: Coercible  n o => n -> o
  unpack = unwrap -- Now using unwrap.
  
```

**Comment by jerbaroo** [comment]
And then two GHC versions later (e.g. GHC 11) remove the deprecated functions, or something like that.

**Comment by andreasabel** [comment]
I am skeptical that renaming these identifiers would be progress for the Haskell Ecosystem as a whole.

I am also skeptical about your proposed migration path:
> ```haskell
> class NewType n o | n -> o where
>   wrap :: o -> n
>   default wrap :: Coercible o n => o -> n
>   wrap = coerce
>   
>   unwrap :: n -> o
>   default unwrap :: Coercible  n o => n -> o
>   unwrap = coerce
>   
>   {-# DEPRECATED #-}
>   pack :: o -> n
>   default pack :: Coercible o n => o -> n
>   pack = wrap -- Now using wrap.
> 
>   {-# DEPRECATED #-}
>   unpack :: n -> o
>   default unpack :: Coercible  n o => n -> o
>   unpack = unwrap -- Now using unwrap.
> ```
I do not see how this would work if someone defines their `instance NewType Foo Bar` implementing `pack` and `unpack`.  These implementations would then be out of sync with `warp` and `unwarp` which are set to `coerce`.

What you would want is that `wrap` and `pack` will be synonyms, no matter which one the user defines.  Further, you would want that both are set to `coerce` if the user does not define either of them.  I do not think that Haskell provides a way to do this.

**Comment by jerbaroo** [comment]
> ... I do not think that Haskell provides a way to do this.

To me this makes the problem even more intriguing that it has been suggested we cannot find a path to rename these functions without breakage in Haskell? Even if we do not rename the functions in this package it is unpleasant to think we cannot do so.

Thank you for taking the time to maintain this project and address issues like these.

Would the following work ? Create top-level functions with a typeclass constraint on `NewType`?

```hs
wrap :: NewType n o => o -> n
wrap = pack

unwrap :: NewType n o => n -> o
unwrap = unpack
```

```hs
class NewType n o | n -> o where
  {-# DEPRECATED #-}
  pack :: NewType n o => o -> n
  ...
```

**Comment by andreasabel** [comment]
Well, but now you got the problem that users would want to create instances using your new names `wrap` and `unwarp`, but they cannot, as these are not class methods.  Moreover, everyone who defines instances gets deprecation warnings (I can imagine, have not tried...).
